### PR TITLE
Updated release number

### PR DESCRIPTION
**Pull request by cpelley**
Fetching the new python-stratify release (https://github.com/SciTools-incubator/python-stratify/issues/19)

### CODE REVIEW

**Comment by cpelley** [comment]
The changes here are quite trivial.  I have requested you both for review so as to provide visibility - I'm happy to merge this PR as is without review but wanted to give you the opportunity to interject.

Cheers

**Comment by pelson** [comment]
@conda-forge-admin, please rerender

**Review by pelson — APPROVED** [review]
Merge when green 👍

**Comment by cpelley** [comment]
Thanks :)

**Comment by cpelley** [comment]
Gosh, really clever with the automated conda forge administrator!

**Comment by bjlittle** [comment]
Awesome, thanks @cpelley !

**Pull request merged**
