### PR TITLE
Bump version to v0.1a2

### PR DESCRIPTION
**Pull request by bjlittle**

### CODE REVIEW

**Comment by bjlittle** [comment]
@ocefpaf Hi! Do you know if it's normal for the `travis-ci` osx job to hang for sooo long without starting? Is it due to limited resource on the travis-ci side, or a conda-forge issue with travis-ci osx builds?

**Comment by ajdawson** [comment]
The osx builds can take a really long time to start (many hours), but I don't know why exactly.

**Comment by bjlittle** [comment]
@ajdawson Thanks for the confirmation. Previously, I've have seen `osx` just taking a royal age to build ... I was hoping that situation might of magically changed, clearly not :cry:

**Comment by ocefpaf** [comment]
It varies a lot. I've waited for weeks once :-(

Since this is building on Windows and Linux I recommend you to merge it
without waiting for osx.

**Comment by bjlittle** [comment]
@ocefpaf If it doesn't build for `osx`, does that mean that this PR change to the feedstock **won't** be available for `osx`, but **will** be available for `windows` and `linux`?

**Comment by ocefpaf** [comment]
No. Travis-CI will be triggered on master and eventually the OS X package
will be uploaded. The only downside is that we won't know about any
possible failures until then.

Since we probably won't get any build failure for a simple version bump we
should be OK. (Even if it is not OK we at least release Win and Linux
first, we fix OS X later.)

**Comment by bjlittle** [comment]
@ocefpaf Thanks. 

Okay, let's roll those dice, I'm feeling lucky today ... :game_die: :game_die: 

... plus I don't have the luxury to wait a couple of weeks for `travis` to catch-up :crossed_fingers:

**Comment by ocefpaf** [comment]
> ... plus I don't have the luxury to wait a couple of weeks for travis to catch-up 🤞

Don't worry. I'm tracking the build on master and I'll fix it in case it fails.

**Pull request merged**
